spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: update
  application:
    name: tasks-service
  datasource:
    url: jdbc:postgresql://localhost:5432/tasks
    username: postgres
    password: postgres
  flyway:
    url: jdbc:postgresql://localhost:5432/tasks
    user: postgres
    password: postgres
    enabled: true
    locations:
      - classpath:db/migration

server:
  port: 8085
